# Generated by Django 3.0.7 on 2020-06-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('titleText', models.CharField(max_length=50)),
                ('streamUrl', models.CharField(max_length=2083)),
                ('redirectionUrl', models.CharField(max_length=2083)),
            ],
        ),
    ]
