# Generated by Django 3.0.7 on 2020-06-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
